# Only the Go backend components are part of the final container image so other components in the monorepo should not be
# part of any generated SBOM from Syft.
exclude:
- ./.github
- ./ui/**
- ./sdks/**
- ./test/**
- ./**/package.json
- ./**/package-lock.json
- ./**/*requirements*.txt
- ./**/setup.py
