ARG SOURCE_CODE=.
ARG TARGETOS=linux
ARG TARGETARCH=amd64

# BUILDPLATFORM is auto-set by BuildKit; do not set a default or GOFIPS140 will panic under QEMU on arm64 Macs
FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:1.26.3@sha256:d36470d5258da00f618b7aca9bdaab8e05134aa938bd6c42d9bd17d50ed45e76 as builder

# Build args to be used at this step
ARG SOURCE_CODE
ARG TARGETOS
ARG TARGETARCH
WORKDIR /workspace

USER root
RUN dnf install -y mailcap

COPY ${SOURCE_CODE}/go.mod .
COPY ${SOURCE_CODE}/go.sum .
COPY ${SOURCE_CODE}/ ./

# Set the /workspace directory as safe for Git
RUN git config --global --add safe.directory /workspace

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build GOTOOLCHAIN=local CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOFIPS140=v1.0.0 go build -tags no_openssl -v -o dist/argoexec ./cmd/argoexec

####################################################################################################
FROM registry.redhat.io/ubi9/ubi-minimal:9.5 AS argoexec

ENV GODEBUG=fips140=on

ARG CI_CONTAINER_VERSION

WORKDIR /bin

COPY --from=builder /workspace/dist/argoexec /bin/
COPY --from=builder /etc/mime.types /etc/mime.types
COPY --from=builder /workspace/hack/ssh_known_hosts /etc/ssh/
COPY --from=builder /workspace/hack/nsswitch.conf /etc/

RUN chmod +x /bin/argoexec

USER 2000

ENTRYPOINT [ "/bin/argoexec" ]
