ARG SOURCE_CODE=.

# Builder args
ARG GIT_COMMIT=unknown
ARG GIT_TAG=unknown
ARG GIT_TREE_STATE=unknown

FROM registry.access.redhat.com/ubi8/go-toolset:1.25@sha256:360613cab609b603c27cc092734493bdbc3e6c88fb84bdbe74706683aaf2cea6 as builder

# Build args to be used at this step
ARG SOURCE_CODE
WORKDIR /workspace

USER root
RUN dnf install -y mailcap

COPY ${SOURCE_CODE}/go.mod .
COPY ${SOURCE_CODE}/go.sum .
COPY ${SOURCE_CODE}/ ./

# Set the /workspace directory as safe for Git
RUN git config --global --add safe.directory /workspace

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build make dist/argoexec GIT_COMMIT=${GIT_COMMIT} GIT_TAG=${GIT_TAG} GIT_TREE_STATE=${GIT_TREE_STATE}


####################################################################################################
FROM registry.redhat.io/ubi8/ubi-minimal@sha256:1352e7792cd20b906b6f3326f2ce714ae9f2ccf6ba06e7132759afa5efe26e3b AS argoexec


ARG CI_CONTAINER_VERSION

LABEL com.redhat.component="odh-data-science-pipelines-argo-argoexec-container" \
      name="managed-open-data-hub/odh-data-science-pipelines-argo-argoexec-rhel8" \
      description="Argo Executor for Argo Workflows used in Data Science Pipelines" \
      summary="odh-data-science-pipelines-argo-argoexec" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.openshift.tags="" \
      io.k8s.display-name="odh-data-science-pipelines-argo-argoexec" \
      io.k8s.description="odh-data-science-pipelines-argo-argoexec" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"

WORKDIR /bin

COPY --from=builder /workspace/dist/argoexec /bin/
COPY --from=builder /etc/mime.types /etc/mime.types
COPY --from=builder /workspace/hack/ssh_known_hosts /etc/ssh/
COPY --from=builder /workspace/hack/nsswitch.conf /etc/

RUN chmod +x /bin/argoexec

USER 2000

ENTRYPOINT [ "/bin/argoexec" ]
