apiVersion: tekton.dev/v1
kind: PipelineRun
#test
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/maas-billing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "stable"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: opendatahub-builds
    appstudio.openshift.io/component: odh-data-science-pipelines-argo-workflowcontroller
    pipelines.appstudio.openshift.io/type: build
  name: odh-data-science-pipelines-argo-workflowcontroller-on-pull-request
  namespace: open-data-hub-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: pr-number
    value: "{{pull_request.number}}"
  - name: output-image
    value: quay.io/opendatahub/ds-pipelines-argo-workflowcontroller:odh-pr
  - name: dockerfile
    value: argo-workflowcontroller/Dockerfile.ODH
  - name: path-context
    value: .
 - name: additional-tags
    value:
    - 'odh-pr-{{revision}}'
  - name: pipeline-type
    value: pull-request
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-data-science-pipelines-argo-workflowcontroller
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
